//! AI Agent Executor Example
//!
//! Demonstrates using nanosandbox to safely execute code generated by AI agents.
//! This is useful for AI coding assistants, autonomous agents, and LLM-based tools.
//!
//! Run with: cargo run --example agent_preset

use nanosandbox::Sandbox;
use std::time::Duration;

fn main() {
    println!("=== AI Agent Executor Example ===\n");

    // Create a temporary workspace
    let workspace = std::env::temp_dir().join("nanosandbox_agent_demo");
    std::fs::create_dir_all(&workspace).unwrap();

    // Write a sample script the "agent" wants to execute
    let script_path = workspace.join("task.py");
    std::fs::write(
        &script_path,
        r#"
import os
import sys

print("Agent task executing...")
print(f"Working directory: {os.getcwd()}")
print(f"Python version: {sys.version}")

# Simulate some computation
result = sum(range(1000))
print(f"Computation result: {result}")

# Write output file
with open("/tmp/result.txt", "w") as f:
    f.write(f"Result: {result}\n")

print("Task completed successfully!")
"#,
    )
    .unwrap();

    // Create sandbox using the agent_executor preset
    // This provides:
    // - Read-write workspace mounted at /workspace
    // - 4GB memory limit
    // - 4 CPU cores
    // - 10 minute timeout
    // - 256 max processes
    let sandbox = Sandbox::agent_executor(&workspace)
        // For AI agents that need API access, whitelist specific domains
        .allow_network(&["api.openai.com", "api.anthropic.com", "*.googleapis.com"])
        // Override timeout for this specific task
        .wall_time_limit(Duration::from_secs(30))
        .build()
        .expect("Failed to create sandbox");

    println!("Sandbox ID: {}", sandbox.id());
    println!("Platform: {}", sandbox.platform());
    println!("Workspace: {:?}\n", workspace);

    // Execute the agent's script
    println!("--- Executing agent task ---");
    let result = sandbox
        .run("python3", &["/workspace/task.py"])
        .expect("Execution failed");

    println!("\nstdout:\n{}", result.stdout);

    if !result.stderr.is_empty() {
        println!("stderr:\n{}", result.stderr);
    }

    println!("--- Execution stats ---");
    println!("Exit code: {}", result.exit_code);
    println!("Duration: {:?}", result.duration);
    if let Some(mem) = result.peak_memory {
        println!("Peak memory: {} KB", mem / 1024);
    }
    if let Some(cpu) = result.cpu_time {
        println!("CPU time: {:?}", cpu);
    }

    // Note: In sandbox, /tmp is isolated from host
    println!("\nTask success: {}", result.success());

    // Example: Execute shell commands (common for agents)
    println!("\n--- Shell command example ---");
    let result = sandbox
        .run("sh", &["-c", "echo 'Files in workspace:' && ls -la /workspace"])
        .unwrap();
    println!("{}", result.stdout);

    // Cleanup
    std::fs::remove_dir_all(&workspace).ok();

    println!("=== Agent example complete ===");
}
